// species.js — static species definitions

'use strict';

// Type advantage chart
// 2.0 = super effective, 0.5 = not very effective, 1.0 = normal
const TYPE_CHART = {
  Fire:     { Fire:0.5, Grass:2.0, Ice:2.0,  Rock:0.5,  Water:0.5, Poison:1.0, Electric:1.0, Flying:1.0, Dark:1.0, Light:1.0, Normal:1.0 },
  Poison:   { Grass:2.0, Light:2.0, Rock:0.5, Water:0.5, Poison:0.5, Fire:1.0, Electric:1.0, Ice:1.0, Flying:1.0, Dark:1.0, Normal:1.0 },
  Electric: { Water:2.0, Flying:2.0, Rock:0.5, Electric:0.5, Grass:0.5, Fire:1.0, Poison:1.0, Ice:1.0, Dark:1.0, Light:1.0, Normal:1.0 },
  Rock:     { Fire:2.0, Ice:2.0, Flying:2.0, Rock:0.5, Poison:0.5, Water:0.5, Grass:0.5, Electric:1.0, Dark:1.0, Light:1.0, Normal:1.0 },
  Water:    { Fire:2.0, Rock:2.0, Water:0.5, Electric:0.5, Grass:0.5, Poison:1.0, Ice:1.0, Flying:1.0, Dark:1.0, Light:1.0, Normal:1.0 },
  Grass:    { Water:2.0, Rock:2.0, Fire:0.5, Poison:0.5, Flying:0.5, Ice:0.5, Electric:1.0, Grass:0.5, Dark:1.0, Light:1.0, Normal:1.0 },
  Ice:      { Grass:2.0, Flying:2.0, Rock:2.0, Fire:0.5, Water:0.5, Ice:0.5, Electric:1.0, Poison:1.0, Dark:1.0, Light:1.0, Normal:1.0 },
  Flying:   { Grass:2.0, Poison:2.0, Rock:0.5, Electric:0.5, Flying:0.5, Fire:1.0, Water:1.0, Ice:1.0, Dark:1.0, Light:1.0, Normal:1.0 },
  Dark:     { Light:2.0, Poison:2.0, Dark:0.5, Electric:1.0, Fire:1.0, Grass:1.0, Water:1.0, Rock:1.0, Flying:1.0, Ice:1.0, Normal:1.0 },
  Light:    { Dark:2.0, Poison:0.5, Light:0.5, Fire:1.0, Water:1.0, Grass:1.0, Rock:1.0, Electric:1.0, Flying:1.0, Ice:1.0, Normal:1.0 },
  Normal:   { Normal:1.0, Fire:1.0, Water:1.0, Grass:1.0, Electric:1.0, Ice:1.0, Rock:1.0, Flying:1.0, Poison:1.0, Dark:1.0, Light:1.0 },
};

// Locus → physical trait + stat mapping
// Dominant = trait present/full, Recessive = absent/diminished
const LOCUS_TRAITS = {
  A: { name: 'Antennae', dominant: 'Long antennae', recessive: 'Stub antennae', stat: 'atk',  domBonus: 8,  recBonus: -3 },
  B: { name: 'Wings',    dominant: 'Full wings',    recessive: 'Vestigial wings', stat: 'spd', domBonus: 7,  recBonus: -4 },
  C: { name: 'Legs',     dominant: '6 legs',        recessive: '4 legs',          stat: 'def', domBonus: 6,  recBonus: -2 },
  D: { name: 'Stinger',  dominant: 'Has stinger',   recessive: 'No stinger',      stat: 'atk', domBonus: 5,  recBonus: 2  },
  E: { name: 'Horns',    dominant: 'Has horns',     recessive: 'No horns',        stat: 'hp',  domBonus: 10, recBonus: -5 },
  // Hidden loci — not shown in UI until discovered
  F: { name: 'Carapace', dominant: 'Thick carapace', recessive: 'Soft carapace',  stat: 'def', domBonus: 12, recBonus: 0, hidden: true },
  G: { name: 'Wingspan',  dominant: 'Large wingspan', recessive: 'Small wingspan', stat: 'spd', domBonus: 9,  recBonus: 0, hidden: true },
};

const ALL_LOCI = ['A', 'B', 'C', 'D', 'E', 'F', 'G'];
const VISIBLE_LOCI = ['A', 'B', 'C', 'D', 'E'];
const HIDDEN_LOCI = ['F', 'G'];

// Species definitions
const SPECIES = {
  SCORCHMITE: {
    id: 'SCORCHMITE',
    name: 'Scorchmite',
    type: 'Fire',
    description: 'A tiny ember-glow beetle. Its carapace smolders faintly in the dark.',
    catchDifficulty: 1,
    baseCatchRate: 0.85,
    baseXpYield: 60,
    baseStats: { hp: { min: 38, max: 52 }, atk: { min: 55, max: 70 }, def: { min: 28, max: 42 }, spd: { min: 50, max: 65 } },
    wildAlleleWeights: { A: 0.65, B: 0.45, C: 0.45, D: 0.70, E: 0.40, F: 0.25, G: 0.20 },
    movePool: ['EMBER', 'SCRATCH', 'FLAME_GLAND', 'SCORCH', 'HEAT_PULSE', 'STINGER'],
    learnAt: { 1: ['EMBER', 'SCRATCH'], 5: ['FLAME_GLAND'], 10: ['SCORCH'], 18: ['HEAT_PULSE'] },
    color: '#e05020',
    emoji: '🪲',
    areas: ['ASHFIELD'],
  },
  BOGSLOG: {
    id: 'BOGSLOG',
    name: 'Bogslog',
    type: 'Poison',
    description: 'A bloated marsh grub that secretes toxic slime.',
    catchDifficulty: 1,
    baseCatchRate: 0.80,
    baseXpYield: 65,
    baseStats: { hp: { min: 55, max: 75 }, atk: { min: 38, max: 52 }, def: { min: 50, max: 68 }, spd: { min: 22, max: 36 } },
    wildAlleleWeights: { A: 0.40, B: 0.45, C: 0.65, D: 0.45, E: 0.70, F: 0.30, G: 0.15 },
    movePool: ['SLIME', 'TACKLE', 'ACID_SPIT', 'BLOAT', 'TOXIC_CLOUD', 'HARDEN'],
    learnAt: { 1: ['SLIME', 'TACKLE'], 5: ['ACID_SPIT'], 10: ['BLOAT'], 18: ['TOXIC_CLOUD'] },
    color: '#608030',
    emoji: '🐛',
    areas: ['ASHFIELD', 'SLAGMIRE'],
  },
  ZAPPFLY: {
    id: 'ZAPPFLY',
    name: 'Zappfly',
    type: 'Electric',
    description: 'A static-charged dragonfly. Its wings crackle with electricity.',
    catchDifficulty: 2,
    baseCatchRate: 0.70,
    baseXpYield: 75,
    baseStats: { hp: { min: 40, max: 55 }, atk: { min: 58, max: 73 }, def: { min: 32, max: 46 }, spd: { min: 60, max: 78 } },
    wildAlleleWeights: { A: 0.68, B: 0.72, C: 0.50, D: 0.40, E: 0.40, F: 0.20, G: 0.35 },
    movePool: ['STATIC_SNAP', 'GUST', 'VOLTBITE', 'ANTENNA_BEAM', 'THUNDERSWARM', 'UPDRAFT'],
    learnAt: { 1: ['STATIC_SNAP', 'GUST'], 5: ['VOLTBITE'], 10: ['ANTENNA_BEAM'], 18: ['THUNDERSWARM'] },
    color: '#a0c000',
    emoji: '🦟',
    areas: ['SHOCKPEAKS'],
  },
  CRUSTWALL: {
    id: 'CRUSTWALL',
    name: 'Crustwall',
    type: 'Rock',
    description: 'An armored pill bug. It rolls into a near-impenetrable ball.',
    catchDifficulty: 2,
    baseCatchRate: 0.68,
    baseXpYield: 80,
    baseStats: { hp: { min: 58, max: 78 }, atk: { min: 42, max: 56 }, def: { min: 68, max: 88 }, spd: { min: 18, max: 30 } },
    wildAlleleWeights: { A: 0.38, B: 0.35, C: 0.72, D: 0.38, E: 0.60, F: 0.55, G: 0.15 },
    movePool: ['SHELL_BASH', 'HARDEN', 'ROCKSLAM', 'CARAPACE_HARDEN', 'BOULDER_ROLL'],
    learnAt: { 1: ['SHELL_BASH', 'HARDEN'], 6: ['ROCKSLAM'], 12: ['CARAPACE_HARDEN'], 20: ['BOULDER_ROLL'] },
    color: '#887050',
    emoji: '🦔',
    areas: ['SLAGMIRE'],
  },
  MISTMOTH: {
    id: 'MISTMOTH',
    name: 'Mistmoth',
    type: 'Water',
    description: 'A pale fog moth with wings perpetually coated in dew.',
    catchDifficulty: 2,
    baseCatchRate: 0.72,
    baseXpYield: 70,
    baseStats: { hp: { min: 48, max: 64 }, atk: { min: 48, max: 63 }, def: { min: 45, max: 60 }, spd: { min: 50, max: 66 } },
    wildAlleleWeights: { A: 0.50, B: 0.65, C: 0.50, D: 0.40, E: 0.50, F: 0.25, G: 0.40 },
    movePool: ['MIST_SPRAY', 'GUST', 'WING_WASH', 'DEWDROP', 'TORRENT', 'UPDRAFT'],
    learnAt: { 1: ['MIST_SPRAY', 'GUST'], 5: ['WING_WASH'], 10: ['DEWDROP'], 18: ['TORRENT'] },
    color: '#7090c0',
    emoji: '🦋',
    areas: ['SLAGMIRE', 'FROSTHOLLOW'],
  },
  BRAMBLESTICK: {
    id: 'BRAMBLESTICK',
    name: 'Bramblestick',
    type: 'Grass',
    description: 'A thorn-covered stick insect that blends into bramble bushes.',
    catchDifficulty: 2,
    baseCatchRate: 0.75,
    baseXpYield: 68,
    baseStats: { hp: { min: 45, max: 60 }, atk: { min: 52, max: 67 }, def: { min: 40, max: 56 }, spd: { min: 45, max: 60 } },
    wildAlleleWeights: { A: 0.45, B: 0.45, C: 0.55, D: 0.68, E: 0.40, F: 0.22, G: 0.22 },
    movePool: ['THORN_JAB', 'SCRATCH', 'SPORE_PUFF', 'VINE_WHIP', 'LEAF_STORM', 'STINGER'],
    learnAt: { 1: ['THORN_JAB', 'SCRATCH'], 5: ['SPORE_PUFF'], 10: ['VINE_WHIP'], 18: ['LEAF_STORM'] },
    color: '#509040',
    emoji: '🌿',
    areas: ['ASHFIELD', 'SHOCKPEAKS'],
  },
  FROSTLURK: {
    id: 'FROSTLURK',
    name: 'Frostlurk',
    type: 'Ice',
    description: 'A translucent cave cricket with frost-encrusted horns.',
    catchDifficulty: 3,
    baseCatchRate: 0.55,
    baseXpYield: 90,
    baseStats: { hp: { min: 55, max: 72 }, atk: { min: 62, max: 80 }, def: { min: 42, max: 58 }, spd: { min: 28, max: 42 } },
    wildAlleleWeights: { A: 0.65, B: 0.35, C: 0.45, D: 0.38, E: 0.72, F: 0.30, G: 0.18 },
    movePool: ['FROST_BITE', 'SCRATCH', 'CRYSTAL_WING', 'COLD_SNAP', 'BLIZZARD_HORN', 'HARDEN'],
    learnAt: { 1: ['FROST_BITE', 'SCRATCH'], 6: ['CRYSTAL_WING'], 13: ['COLD_SNAP'], 22: ['BLIZZARD_HORN'] },
    color: '#80c0e0',
    emoji: '🦗',
    areas: ['FROSTHOLLOW'],
  },
  DUSKWING: {
    id: 'DUSKWING',
    name: 'Duskwing',
    type: 'Flying',
    description: 'A shadow moth whose wings absorb light. Nearly invisible at dusk.',
    catchDifficulty: 3,
    baseCatchRate: 0.50,
    baseXpYield: 95,
    baseStats: { hp: { min: 42, max: 57 }, atk: { min: 55, max: 72 }, def: { min: 38, max: 52 }, spd: { min: 68, max: 86 } },
    wildAlleleWeights: { A: 0.45, B: 0.78, C: 0.42, D: 0.38, E: 0.42, F: 0.25, G: 0.62 },
    movePool: ['GUST', 'VOID_BITE', 'DIVE_STRIKE', 'UPDRAFT', 'WING_STORM'],
    learnAt: { 1: ['GUST', 'VOID_BITE'], 7: ['DIVE_STRIKE'], 14: ['UPDRAFT'], 22: ['WING_STORM'] },
    color: '#604080',
    emoji: '🦇',
    areas: ['VOIDRIFT'],
  },
  VOIDGRUB: {
    id: 'VOIDGRUB',
    name: 'Voidgrub',
    type: 'Dark',
    description: 'A deep-earth larva with an all-consuming appetite and inky hide.',
    catchDifficulty: 3,
    baseCatchRate: 0.52,
    baseXpYield: 92,
    baseStats: { hp: { min: 55, max: 72 }, atk: { min: 58, max: 75 }, def: { min: 48, max: 64 }, spd: { min: 40, max: 55 } },
    wildAlleleWeights: { A: 0.62, B: 0.42, C: 0.65, D: 0.42, E: 0.45, F: 0.28, G: 0.22 },
    movePool: ['BURROW', 'TACKLE', 'VOID_BITE', 'SHADOW_COIL', 'ABYSS_STRIKE'],
    learnAt: { 1: ['BURROW', 'TACKLE'], 7: ['VOID_BITE'], 14: ['SHADOW_COIL'], 22: ['ABYSS_STRIKE'] },
    color: '#303050',
    emoji: '🐜',
    areas: ['VOIDRIFT'],
  },
  LUMIBEETLE: {
    id: 'LUMIBEETLE',
    name: 'Lumibeetle',
    type: 'Light',
    description: 'A rare bioluminescent scarab of immense power. Said to appear only once a generation.',
    catchDifficulty: 5,
    baseCatchRate: 0.08,
    baseXpYield: 150,
    baseStats: { hp: { min: 68, max: 90 }, atk: { min: 70, max: 92 }, def: { min: 62, max: 82 }, spd: { min: 65, max: 85 } },
    wildAlleleWeights: { A: 0.78, B: 0.75, C: 0.78, D: 0.75, E: 0.80, F: 0.60, G: 0.55 },
    movePool: ['GLIMMER', 'LUMEN_STRIKE', 'RADIATE', 'SOLAR_BURST', 'CARAPACE_HARDEN'],
    learnAt: { 1: ['GLIMMER', 'LUMEN_STRIKE'], 8: ['RADIATE'], 16: ['CARAPACE_HARDEN'], 25: ['SOLAR_BURST'] },
    color: '#e0d060',
    emoji: '✨',
    areas: ['LUMINARA'],
  },
};

// Exploration areas
const AREAS = {
  ASHFIELD: {
    id: 'ASHFIELD',
    name: 'Ashfield',
    description: 'Dry, sun-baked grassland at the edge of town. Perfect for beginners.',
    unlocked: true,
    stepsRange: [3, 8],
    encounterTable: [
      { speciesId: 'SCORCHMITE',   weight: 45, levelRange: [2, 7]  },
      { speciesId: 'BOGSLOG',      weight: 35, levelRange: [2, 6]  },
      { speciesId: 'BRAMBLESTICK', weight: 20, levelRange: [2, 6]  },
    ],
  },
  SLAGMIRE: {
    id: 'SLAGMIRE',
    name: 'Slagmire',
    description: 'A murky swamp reeking of sulfur. Hardier bugs lurk here.',
    unlocked: false,
    unlockCondition: { monstersOwned: 3 },
    stepsRange: [2, 6],
    encounterTable: [
      { speciesId: 'BOGSLOG',    weight: 40, levelRange: [5, 11] },
      { speciesId: 'CRUSTWALL', weight: 35, levelRange: [4, 10] },
      { speciesId: 'MISTMOTH',  weight: 25, levelRange: [4, 9]  },
    ],
  },
  SHOCKPEAKS: {
    id: 'SHOCKPEAKS',
    name: 'Shockpeaks',
    description: 'Jagged mountain tops constantly struck by lightning.',
    unlocked: false,
    unlockCondition: { defeatedTrainer: 'RIVAL_1' },
    stepsRange: [3, 7],
    encounterTable: [
      { speciesId: 'ZAPPFLY',      weight: 50, levelRange: [8, 14]  },
      { speciesId: 'BRAMBLESTICK', weight: 30, levelRange: [8, 13]  },
      { speciesId: 'SCORCHMITE',   weight: 20, levelRange: [9, 14]  },
    ],
  },
  FROSTHOLLOW: {
    id: 'FROSTHOLLOW',
    name: 'Frosthollow',
    description: 'A glacial cave system where temperatures drop below freezing.',
    unlocked: false,
    unlockCondition: { minGeneration: 2 },
    stepsRange: [3, 7],
    encounterTable: [
      { speciesId: 'FROSTLURK', weight: 50, levelRange: [12, 18] },
      { speciesId: 'MISTMOTH',  weight: 30, levelRange: [11, 17] },
      { speciesId: 'CRUSTWALL', weight: 20, levelRange: [12, 17] },
    ],
  },
  VOIDRIFT: {
    id: 'VOIDRIFT',
    name: 'Voidrift',
    description: 'A deep fissure where light never reaches. Strange things dwell here.',
    unlocked: false,
    unlockCondition: { defeatedTrainer: 'RIVAL_2' },
    stepsRange: [2, 5],
    encounterTable: [
      { speciesId: 'VOIDGRUB', weight: 50, levelRange: [16, 24] },
      { speciesId: 'DUSKWING', weight: 50, levelRange: [16, 24] },
    ],
  },
  LUMINARA: {
    id: 'LUMINARA',
    name: 'Luminara',
    description: 'A hidden grove that glows softly at night. The rarest bugs converge here.',
    unlocked: false,
    unlockCondition: { minGeneration: 3, minDominantLoci: 3 },
    stepsRange: [5, 12],
    encounterTable: [
      { speciesId: 'LUMIBEETLE', weight: 100, levelRange: [22, 30] },
    ],
  },
};
